name: Build and Upload Python Package

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Get asset name
        id: asset_name_getter
        run: |
          VERSION=${{ github.event.release.tag_name }} && VERSION=${VERSION#v}
          echo "VERSION_NUM=$VERSION" >> $GITHUB_OUTPUT
          echo "ASSET_NAME=macprefs-$VERSION.tar.gz" >> $GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Setup PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.8
          architecture: x64
          update-python: true
          cache: true
          cache-dependency-path: ./pdm.lock

      - name: Build project
        run: pdm build

      - name: debug
        uses: hmarr/debug-action@v2

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/${{ steps.asset_name_getter.outputs.ASSET_NAME }}
          asset_name: ${{ steps.asset_name_getter.outputs.ASSET_NAME }}
          asset_content_type: application/gzip

      - name: Update Local Homebrew Formula
        run: |
          URL="${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ steps.asset_name_getter.outputs.ASSET_NAME }}"
          SHA256=$(cat ./dist/${{ steps.asset_name_getter.outputs.ASSET_NAME }} | shasum -a 256 | cut -f 1 -d ' ')
          VERSION=${{ steps.asset_name_getter.outputs.VERSION_NUM }}
          if [ "$RUNNER_OS" == "macOS" ]; then
            sed -i "" "s|^  url \".*\"|  url \"$URL\"|" ./Formula/macprefs.rb
            sed -i "" "s/^  version \".*\"/  version \"$VERSION\"/" ./Formula/macprefs.rb
            sed -i "" "s/^  sha256 \".*\"/  sha256 \"$SHA256\"/" ./Formula/macprefs.rb
          else
            sed -i "s|^  url \".*\"|  url \"$URL\"|" ./Formula/macprefs.rb
            sed -i "s/^  version \".*\"/  version \"$VERSION\"/" ./Formula/macprefs.rb
            sed -i "s/^  sha256 \".*\"/  sha256 \"$SHA256\"/" ./Formula/macprefs.rb
          fi
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./Formula/macprefs.rb
          git commit -m "Auto update version and sha256 for release ${{ github.event.release.tag_name }}"
          git push origin master

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Push Homebrew Formula
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TAP_TOKEN }}
        with:
          source_file: ./Formula/macprefs.rb
          destination_repo: sijanc147/homebrew-formulas
          destination_folder: Formula
          user_email: seanbugeja23@gmail.com
          user_name: Sean Bugeja
          commit_message: "Auto update version and sha256 for release ${{ github.event.release.tag_name }}"
