name: Build and Upload Python Package

on:
  push:
    branches:
      - master
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install PDM
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          pip install pdm

      - name: Build Python package
        run: |
          pdm build

      - name: debug
        uses: hmarr/debug-action@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dist/*.tar.gz
