name: Build and Upload Python Package

on:
  release:
    types: [published]

env:
  RELEASE-ASSET: macprefs-${{ github.event.release.tag_name }}.tar.gz

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get asset name
        id: asset_name
        run: |
          echo "::set-output name=asset_name::macprefs-$(echo ${GITHUB_REF_NAME#v}).tar.gz"

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.target_commitish }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install PDM
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          pip install pdm

      - name: Build Python package
        run: |
          pdm build

      - name: debug
        uses: hmarr/debug-action@v2

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./dist/${{ steps.asset_name.outputs.asset_name }}
          asset_name: ${{ steps.asset_name.outputs.asset_name }}
          asset_content_type: application/gzip

      - name: Update Local Homebrew Formula
        run: |
          URL="${{ github.event.repository.html_url }}/releases/download/${{ github.event.release.tag_name }}/${{ steps.asset_name.outputs.asset_name }}"
          SHA256=$(cat ./dist/${{ steps.asset_name.outputs.asset_name }} | shasum -a 256 | cut -f 1 -d ' ')
          VERSION=${{ github.event.release.tag_name }} && VERSION=${VERSION#v}
          sed -i "s|^  url \".*\"|  url \"$URL\"|" ./Formula/macprefs.rb
          sed -i "s/^  version \".*\"/  version \"$VERSION\"/" ./Formula/macprefs.rb
          sed -i "s/^  sha256 \".*\"/  sha256 \"$SHA256\"/" ./Formula/macprefs.rb
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./Formula/macprefs.rb
          git commit -m "Auto update version and sha256 for release ${{ github.event.release.tag_name }}"
          git push origin master

      - name: Push Homebrew Formula
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PERSONAL_TAP_TOKEN }}
        with:
          source_file: ./Formula/macprefs.rb
          destination_repo: sijanc147/homebrew-formulas
          destination_folder: Formula
          user_email: seanbugeja23@gmail.com
          user_name: Sean Bugeja
          commit_message: "Auto update version and sha256 for release ${{ github.event.release.tag_name }}"
